(function(){
'use strict';
angular.module('fraudDetectionModule')
.constant('fraudConstants',{
API_ENDPOINTS:{
RISK_SCORE:'/api/fraud/risk-score',
POLICY_THRESHOLDS:'/api/policy/thresholds',
AUDIT_LOG:'/api/audit/log',
TRANSACTION_INGEST:'/api/transaction/ingest',
UPDATE_THRESHOLD:'/api/policy/threshold/update'
},
RISK_LEVELS:{
LOW:'low',
MEDIUM:'medium',
HIGH:'high',
CONFIRMED_FRAUD:'confirmed_fraud'
},
ACTIONS:{
APPROVE:'approve',
ALERT:'alert',
STEP_UP:'step_up',
HOLD:'hold',
DECLINE:'decline'
},
DEFAULT_THRESHOLDS:[
{riskLevel:'low',minScore:0,maxScore:30,action:'approve',isActive:true},
{riskLevel:'medium',minScore:31,maxScore:60,action:'alert',isActive:true},
{riskLevel:'high',minScore:61,maxScore:85,action:'hold',isActive:true},
{riskLevel:'confirmed_fraud',minScore:86,maxScore:100,action:'decline',isActive:true}
]
});
})();