describe('dataService', function() {
    var dataService;

    beforeEach(module('creditCardDashboardApp'));

    beforeEach(inject(function(_dataService_) {
        dataService = _dataService_;
    }));

    it('should expose getCreditCards and getTransactions API', function() {
        // Arrange & Act
        // Service injected in beforeEach.

        // Assert
        expect(typeof dataService.getCreditCards).toBe('function');
        expect(typeof dataService.getTransactions).toBe('function');
    });

    it('should return a non-empty list of credit cards', function() {
        // Arrange & Act
        var cards = dataService.getCreditCards();

        // Assert
        expect(Array.isArray(cards)).toBe(true);
        expect(cards.length).toBeGreaterThan(0);
        cards.forEach(function(card) {
            expect(card.id).toBeDefined();
            expect(card.cardName).toBeDefined();
            expect(card.bank).toBeDefined();
            expect(card.cardNumber).toBeDefined();
            expect(card.creditLimit).toBeDefined();
            expect(card.availableCredit).toBeDefined();
            expect(card.outstanding).toBeDefined();
            expect(card.billingDate).toBeDefined();
            expect(card.dueDate).toBeDefined();
        });
    });

    it('should return a non-empty list of transactions with expected fields', function() {
        // Arrange & Act
        var txs = dataService.getTransactions();

        // Assert
        expect(Array.isArray(txs)).toBe(true);
        expect(txs.length).toBeGreaterThan(0);
        txs.forEach(function(tx) {
            expect(tx.id).toBeDefined();
            expect(tx.date).toBeDefined();
            expect(tx.merchant).toBeDefined();
            expect(tx.amount).toBeDefined();
            expect(tx.category).toBeDefined();
            expect(tx.cardId).toBeDefined();
            expect(tx.reference).toBeDefined();
        });
    });

    it('should return different transaction references and valid dates', function() {
        // Arrange & Act
        var txs = dataService.getTransactions();

        // Assert
        var references = {};
        txs.forEach(function(tx) {
            expect(references[tx.reference]).toBeUndefined();
            references[tx.reference] = true;

            var dateValue = new Date(tx.date).getTime();
            expect(isNaN(dateValue)).toBe(false);
        });
    });

    it('should keep transactions immutable across calls', function() {
        // Arrange
        var firstCall = dataService.getTransactions();

        // Act
        firstCall[0].merchant = 'Changed Merchant';
        var secondCall = dataService.getTransactions();

        // Assert
        expect(secondCall[0].merchant).not.toBe('Changed Merchant');
    });

    it('should return consistent credit cards data across calls', function() {
        // Arrange
        var firstCards = dataService.getCreditCards();
        var secondCards = dataService.getCreditCards();

        // Act & Assert
        expect(firstCards).toEqual(secondCards);
    });

    it('should have transactions amounts within expected range', function() {
        // Arrange & Act
        var txs = dataService.getTransactions();

        // Assert
        txs.forEach(function(tx) {
            expect(tx.amount).toBeGreaterThanOrEqual(5);
            expect(tx.amount).toBeLessThanOrEqual(250);
        });
    });

});

/*
Test Documentation:
- Test Name: dataService API and data integrity
- Purpose: Validate that dataService exposes the expected API and returns consistent, well-formed mock data.
- Scenario:
  - Service API existence.
  - Credit card list structure and contents.
  - Transactions list structure, uniqueness of references, and valid dates.
  - Immutability and consistency of returned data.
  - Amount boundary checks.
- Expected Result:
  - dataService exposes getCreditCards and getTransactions.
  - Returned data structures contain all necessary fields and respect expected ranges.
  - Subsequent calls to getCreditCards return identical arrays, while mutations on the returned transactions do not affect future calls.
*/

/*
Coverage Report:
- Functions tested:
  - getCreditCards.
  - getTransactions.
- Statements covered:
  - Access to creditCards constant.
  - Access to transactions generated by generateTransactions.
  - Generation properties indirectly via transaction fields and ranges.
- Branches covered:
  - Implicit branches in generateTransactions for random merchant and card selection (validated via field existence and ranges).
- Error scenarios covered:
  - Basic validation against NaN dates and missing fields, which would indicate generation issues.
- Uncovered scenarios:
  - Exhaustive validation of random distribution of merchants and cards.
  - Behavior if generateTransactions were to throw or return malformed data (not currently simulated).
  - PCI-related constraints beyond structure (e.g., masking format checks on cardNumber).
*/